<!-- 회원 정보

CREATE TABLE MEMEBER 
(
  MEMID VARCHAR2(50) NOT NULL 
, MEMPW VARCHAR2(50) 
, MEMNAME VARCHAR2(30) 
, MEMPHONE VARCHAR2(30) 
, MEMADDR VARCHAR2(100) 
, MEMNUM NUMBER NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    MEMID 
  , MEMNUM 
  )
  ENABLE 
);


시퀀스 생성

CREATE SEQUENCE MEMNUM_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;


 -->